name: auto-merge-deps

on:
  pull_request_target:

jobs:
  auto-merge:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ahmadnassri/action-dependabot-auto-merge@v2.6
        with:
          github-token: ${{ secrets.GH_PAT }}
